// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcvztyMvM2es9y1gFnX7RW54TyqfLc3L8',
    appId: '1:775487623656:web:bb954ce0e3202dd921945d',
    messagingSenderId: '775487623656',
    projectId: 'daka-izleme',
    authDomain: 'daka-izleme.firebaseapp.com',
    storageBucket: 'daka-izleme.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDh_Ke9_iT4XL6vfvQut4q7Ucs-rq2NXF8',
    appId: '1:775487623656:android:2a5075a1faa835bd21945d',
    messagingSenderId: '775487623656',
    projectId: 'daka-izleme',
    storageBucket: 'daka-izleme.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdlJs1El7IV8uI2z-tGHbhMTmiHR7fgJA',
    appId: '1:775487623656:ios:5e4d39c130010e9c21945d',
    messagingSenderId: '775487623656',
    projectId: 'daka-izleme',
    storageBucket: 'daka-izleme.firebasestorage.app',
    iosBundleId: 'com.example.dakaizleme',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdlJs1El7IV8uI2z-tGHbhMTmiHR7fgJA',
    appId: '1:775487623656:ios:5e4d39c130010e9c21945d',
    messagingSenderId: '775487623656',
    projectId: 'daka-izleme',
    storageBucket: 'daka-izleme.firebasestorage.app',
    iosBundleId: 'com.example.dakaizleme',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAcvztyMvM2es9y1gFnX7RW54TyqfLc3L8',
    appId: '1:775487623656:web:4a1e230ecdb253d821945d',
    messagingSenderId: '775487623656',
    projectId: 'daka-izleme',
    authDomain: 'daka-izleme.firebaseapp.com',
    storageBucket: 'daka-izleme.firebasestorage.app',
  );
}
